spring.application.name=OwncloudSelfApi

server.port= 8085

owncloud.url=http://localhost/remote.php/dav/files/AdminCloud/
owncloud.username=AdminCloud
owncloud.password=Server1492@


upload.server.dir= /opt/uploads


# Tamaño máximo por archivo
spring.servlet.multipart.max-file-size=800MB

# Tamaño máximo de la solicitud completa
spring.servlet.multipart.max-request-size=800MB