spring.application.name=OwncloudSelfApi

server.port= 8085

owncloud.url=http://localhost/remote.php/dav/files/AdminCloud/
owncloud.username=AdminCloud
owncloud.password=Server1492@


upload.server.dir= /opt/uploads